sudo: false

language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - client/node_modules/

scala:
   - 2.11.3

jdk:
  - oraclejdk8

install:
  - ./install_dependencies.sh

script:
  - PROJECT_ROOT=$(pwd)
  - echo "\nStarting server test\n"
  - cd $PROJECT_ROOT/server
  - sbt clean coverage test
  - sbt coverageAggregate
  - echo "\nStarting client test\n"
  - cd $PROJECT_ROOT/client
  # We need to tell npm that we use the local installation of grunt
  # We do not install grunt globally because this would prevent us from using the
  # container based travis ci infrastructure
  - ./node_modules/.bin/grunt test

after_success:
  - cd $PROJECT_ROOT/server
  - sbt coveralls
