sudo: false

language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

scala:
   - 2.11.3

jdk:
  - oraclejdk8

install:
  - ./install_dependencies.sh

script:
  - cd && cd server &&
    sbt clean coverage test &&
    sbt coverageAggregate
  - cd && cd client &&
    grunt test

after_success:
  - cd server &&
    sbt coveralls
