sudo: false

language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

scala:
   - 2.11.3

jdk:
  - oraclejdk8

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - cd && cd client && npm install bower grunt-cli && bower install
  - cd && cd server && sbt update

script:
  - cd && cd server &&
    sbt clean coverage test &&
    sbt coverageAggregate
  - cd && cd client &&
    grunt test

after_success:
  - cd server &&
    sbt coveralls
