sudo: false

language: scala

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - client/node_modules/

scala:
   - 2.11.3

jdk:
  - oraclejdk8

install:
  - ./install_dependencies.sh

script:
  - ./ci-test.sh

after_success:
  - cd $PROJECT_ROOT/server
  - sbt coveralls
